# Generated by Django 4.2 on 2023-05-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='purchased',
            field=models.BooleanField(default=True),
        ),
    ]
