# Generated by Django 4.2 on 2023-04-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, choices=[('I', 'Important'), ('U', 'Urgent'), ('T', 'Todo'), ('L', 'Lesson Note')], max_length=1, null=True)),
            ],
        ),
    ]
