# Generated by Django 4.2 on 2023-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
