# Generated by Django 4.2 on 2023-05-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='hight',
            new_name='height',
        ),
    ]
